/**
 * Auto-generated by @tanstack/router-plugin in dev.
 *
 * This shim lets the dashboard build before the plugin runs.  Run
 *   `pnpm dev` once with the TanStack Router plugin enabled and this
 * file will be regenerated from the file-based routes in `src/routes/`.
 */

import { rootRouteWithContext, createRoute } from '@tanstack/react-router';
import type { QueryClient } from '@tanstack/react-query';

import { Route as RootRoute } from './routes/__root';
import { Route as IndexRoute } from './routes/index';
import { Route as TransactionsRoute } from './routes/transactions';
import { Route as EndpointsRoute } from './routes/endpoints';
import { Route as AgentsRoute } from './routes/agents';
import { Route as ComplianceRoute } from './routes/compliance';
import { Route as WebhooksRoute } from './routes/webhooks';
import { Route as DirectoryRoute } from './routes/directory';
import { Route as SettingsRoute } from './routes/settings';
import { Route as OnboardingRoute } from './routes/onboarding';

void rootRouteWithContext<{ queryClient: QueryClient }>();
void createRoute;

export const routeTree = RootRoute.addChildren([
  IndexRoute,
  TransactionsRoute,
  EndpointsRoute,
  AgentsRoute,
  ComplianceRoute,
  WebhooksRoute,
  DirectoryRoute,
  SettingsRoute,
  OnboardingRoute,
]);
